"""create logs table

Revision ID: 53b848dc6476
Revises: 
Create Date: 2025-05-12 16:31:32.816985

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b848dc6476'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###